import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import Header from "@/components/layout/Header";
import { ReduxProvider } from "./provider"; // Ensure ReduxProvider is a client component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata export for server component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Removed "use client"
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ height: '100vh' }}
      >
        <div className="h-screen bg-gray-100 flex flex-col justify-between items-center">
          <div className="bg-[#000] max-w-[480px] w-full rounded shadow-lg flex flex-col items-center flex-wrap">
            <Header />
          </div>
          <ReduxProvider>{children}</ReduxProvider>
          <div className="bg-black max-w-[480px] w-full">
            <h3 className="text-white text-center">Hello</h3>
          </div>
        </div>
      </body>
    </html>
  );
}
