import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import Header from "@/components/layout/Header";
import FooterNav from "@/components/layout/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata export for server component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Removed "use client"
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ height: '100vh' }}
      >
        <div className="h-screen bg-gray-100 flex flex-col justify-between">
          <div className="sticky top-0 z-10 flex justify-center">
            <Header />
          </div>
          <main className="flex-grow flex justify-center">
            {children}
          </main>
          <div className="sticky bottom-0 bg-gray-100 z-10 flex justify-center">
            <FooterNav />
          </div>
        </div>
      </body>
    </html>
  );
}
